# -*- coding: utf-8 -*-
"""CODECRAFT_SD_04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xfRCmMAeMpLL1CYTdZ4t7XFQ5DMDvUa7
"""

import random
num = random.randint(1,1000)
attempts = 1
guess = int(input("can you guess the number . i am thinking ? it is less then 1000\n"))
while num!= guess:
    attempts += 1
    if guess > num:
        print("your guess in higher")
        guess = int(input("guess again: "))
    elif guess < num:
        print("your guess in lower")
        guess = int(input("guess again: "))
print ("you won in "+ str(attempts) + " attempts")